[package]
name = "syndiff"
description = "reserved"
version = "0.1.0"
license = "MIT"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
tree-sitter = "0.26.3"
strsim = "0.11.1"
rustc-hash = "2.1.1"
imara-diff = "0.2.0"
