name: CI

on:
  push:
    branches: [main]
  pull_request:
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

jobs:
  linux-ci:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: ["stable", "beta", "nightly", "1.87.0"]
        include:
          - toolchain: stable
            fuzz: 1
          - toolchain: beta
            fuzz: 1
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Cargo build
        run: cargo build --verbose

      - name: Cargo test
        run: cargo nextest run --verbose

      - name: Cargo doctest
        run: cargo test --doc --verbose

      - name: Cargo check w/o default features
        if: matrix.toolchain == 'nightly'
        run: cargo check --verbose --no-default-features

      - name: Cargo test all features
        if: matrix.toolchain == 'nightly'
        run: cargo nextest run --verbose --all-features

      - name: Cargo doctest all features
        if: matrix.toolchain == 'nightly'
        run: cargo test --doc --verbose --all-features

  build_result:
    name: homu build finished
    runs-on: ubuntu-latest
    needs:
      - "linux-ci"

    steps:
      - name: Mark the job as successful
        run: exit 0
        if: success()
      - name: Mark the job as unsuccessful
        run: exit 1
        if: "!success()"
